name: compile Wakatime stats of a month

on:
  push:
    branches:
      - main
  schedule:
    - cron: "05 00 01 * *" # At 00:05 AM on first day of the month

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: python compile-monthly-stats.py

      - name: commit & push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Compile Monthly Stats
