name: fetch Wakatime stats

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "05 00 * * *" # everyday at 00:05 AM

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python main.py
        env:
          WAKATIME_API_KEYS: ${{ secrets.WAKATIME_API_KEYS }}

      - name: commit & push
        uses: stefanzweifel/git-auto-commit-action@v4
